-- Core payroll schema.
-- Money is NUMERIC(14,2); never floating point.

CREATE TABLE departments (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(20)  NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE employees (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_code    VARCHAR(20)  NOT NULL UNIQUE,
    first_name       VARCHAR(60)  NOT NULL,
    last_name        VARCHAR(60)  NOT NULL,
    email            VARCHAR(160) NOT NULL UNIQUE,
    hire_date        DATE         NOT NULL,
    termination_date DATE,
    status           VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    department_id    BIGINT       REFERENCES departments (id),
    base_salary      NUMERIC(14, 2) NOT NULL,
    CONSTRAINT employees_status_chk      CHECK (status IN ('ACTIVE', 'ON_LEAVE', 'TERMINATED')),
    CONSTRAINT employees_base_salary_chk CHECK (base_salary >= 0),
    CONSTRAINT employees_term_date_chk   CHECK (termination_date IS NULL OR termination_date >= hire_date)
);

CREATE INDEX idx_employees_department ON employees (department_id);
CREATE INDEX idx_employees_status     ON employees (status);

CREATE TABLE pay_periods (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_start DATE        NOT NULL,
    period_end   DATE        NOT NULL,
    pay_date     DATE        NOT NULL,
    status       VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    CONSTRAINT pay_periods_range_chk  CHECK (period_end >= period_start),
    CONSTRAINT pay_periods_status_chk CHECK (status IN ('OPEN', 'PROCESSING', 'PAID', 'CLOSED')),
    CONSTRAINT pay_periods_range_uq   UNIQUE (period_start, period_end)
);

CREATE TABLE payslips (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id      BIGINT      NOT NULL REFERENCES employees (id),
    pay_period_id    BIGINT      NOT NULL REFERENCES pay_periods (id),
    gross_pay        NUMERIC(14, 2) NOT NULL DEFAULT 0,
    total_deductions NUMERIC(14, 2) NOT NULL DEFAULT 0,
    net_pay          NUMERIC(14, 2) NOT NULL DEFAULT 0,
    status           VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    generated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT payslips_gross_chk      CHECK (gross_pay >= 0),
    CONSTRAINT payslips_deductions_chk CHECK (total_deductions >= 0),
    CONSTRAINT payslips_status_chk     CHECK (status IN ('DRAFT', 'APPROVED', 'PAID'))
);

-- One payslip per employee per period.
ALTER TABLE payslips ADD CONSTRAINT payslips_employee_period_unique UNIQUE (employee_id, pay_period_id);

CREATE INDEX idx_payslips_period ON payslips (pay_period_id);

CREATE TABLE payslip_lines (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payslip_id     BIGINT      NOT NULL REFERENCES payslips (id) ON DELETE CASCADE,
    component_code VARCHAR(30) NOT NULL,
    component_type VARCHAR(20) NOT NULL,
    description    VARCHAR(200),
    amount         NUMERIC(14, 2) NOT NULL,
    CONSTRAINT payslip_lines_type_chk   CHECK (component_type IN ('EARNING', 'DEDUCTION')),
    CONSTRAINT payslip_lines_amount_chk CHECK (amount >= 0)
);

CREATE INDEX idx_payslip_lines_payslip ON payslip_lines (payslip_id);
