-- Bookkeeping for payroll data pulled from the external HRMS (Workday-style) API.
-- Every fetch attempt is auditable: what was pulled, what was written, what was
-- rejected and why, and how the upstream API failed when it did.

CREATE TABLE ingestion_runs (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source            VARCHAR(40)  NOT NULL,
    trigger_type      VARCHAR(20)  NOT NULL,
    status            VARCHAR(30)  NOT NULL,
    period_start      DATE,
    period_end        DATE,
    started_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    finished_at       TIMESTAMPTZ,
    employees_fetched INTEGER      NOT NULL DEFAULT 0,
    employees_written INTEGER      NOT NULL DEFAULT 0,
    payslips_fetched  INTEGER      NOT NULL DEFAULT 0,
    payslips_written  INTEGER      NOT NULL DEFAULT 0,
    records_rejected  INTEGER      NOT NULL DEFAULT 0,
    http_attempts     INTEGER      NOT NULL DEFAULT 0,
    failure_kind      VARCHAR(40),
    failure_detail    TEXT,
    CONSTRAINT ingestion_runs_status_chk CHECK (
        status IN ('RUNNING', 'SUCCEEDED', 'PARTIAL', 'FAILED')),
    CONSTRAINT ingestion_runs_trigger_chk CHECK (
        trigger_type IN ('MANUAL', 'SCHEDULED')),
    CONSTRAINT ingestion_runs_period_chk CHECK (
        period_end IS NULL OR period_start IS NULL OR period_end >= period_start)
);

CREATE INDEX idx_ingestion_runs_started ON ingestion_runs (started_at DESC);
CREATE INDEX idx_ingestion_runs_status  ON ingestion_runs (status);

-- Records the HRMS rows we deliberately refused to write, so a bad upstream
-- record is visible rather than silently dropped.
CREATE TABLE ingestion_run_errors (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id      BIGINT       NOT NULL REFERENCES ingestion_runs (id) ON DELETE CASCADE,
    record_type VARCHAR(20)  NOT NULL,
    external_id VARCHAR(100),
    reason      VARCHAR(500) NOT NULL,
    CONSTRAINT ingestion_run_errors_type_chk CHECK (record_type IN ('WORKER', 'PAYSLIP'))
);

CREATE INDEX idx_ingestion_run_errors_run ON ingestion_run_errors (run_id);

-- Freshness markers so a stale row is distinguishable from one the last run touched.
ALTER TABLE employees ADD COLUMN last_synced_at TIMESTAMPTZ;
ALTER TABLE payslips  ADD COLUMN last_synced_at TIMESTAMPTZ;
